version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  reviewers:
  - nbprojekt
  assignees:
  - nbprojekt
  labels:
  - Dependencies
  - Bot
  ignore:
  - dependency-name: "@angular-devkit/architect"
    versions:
    - "> 0.801.3, < 1"
  - dependency-name: "@angular-devkit/architect"
    versions:
    - ">= 0.901.a, < 0.902"
