name: Android CI

on: 
  push:
    branches:    
    - 'master'

jobs:
  build:

    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci 
      - name: Install global packages
        run: i -g ionic cordova   
      - name: Add android platform
        run: ionic cordova resources && ionic cordova platform add android

      - name: Build APK
        run: ionic cordova build android --prod 
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: stack-app
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
