name: Android
on:
  push:
    branches:
      - master

jobs:
  generate-apk:
    if: "!contains(github.event.head_commit.message, 'skip build')"
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Java 8.x
      uses: actions/setup-java@v1
      with:
        java-version: 8.x
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install npm dependencies
      run: npm ci && npm i -g ionic cordova
    - name: Add android platform
      run: ionic cordova resources && ionic cordova platform add android
    - name: Build APK
      run: ionic cordova build android --prod
    - name: Rename APK
      run: mv platforms/android/app/build/outputs/apk/debug/app-debug.apk ./${{secrets.APP_NAME}}.apk
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: ${{secrets.APP_NAME}}
        path: ${{secrets.APP_NAME}}.apk
