name: Code quality
on: 
  pull_request:
    types: [labeled]
    branches:
      - master      

jobs:
  packageSize:
    if: "contains(github.event.pull_request.labels.*.name, 'dependencies')"
    name: Check package size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: carlesnunez/check-my-bundlephobia@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          strict: false
          threshold: 50000
