
name: Github Todos
on:
  push:
    branches:
      - master
      
todo-to-issue:
  todo-to-issue:
    name: TODO to Issue
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@master"
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v2.0"
      with:
        REPO: ${{ github.repository }}
        BEFORE: ${{ github.event.before }}
        SHA: ${{ github.sha }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL: "// TODO"
        COMMENT_MARKER: "//"
