name: Github CI
on: 
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:
  wip:
    name: Test github events
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: echo "$GITHUB_CONTEXT" 
  lint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Run typescript linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npx ng lint
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Run ionic production build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build production
      run: npx ionic build --prod
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Run karma unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Unit tests
      run: npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      continue-on-error: true
