name: Gource
on:
  schedule:
    - cron:  '0 0 1 * *'
    
jobs:
  Gource:
    name: Create and uplaod gource video
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          gource_title: 'Stack App'
          logo_url: 'https://raw.githubusercontent.com/NBprojekt/stack-app/master/src/assets/icon/favicon.png'


      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4
