name: iOS CI

on: 
  push:
    branches:    
    - 'master'
  pull_request:
    branches:
      - master
 
jobs:
  build:

    name: Build iOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install and run xcodegen
      run: |
        brew install xcodegen
        xcodegen generate
        
    - name: Install dependencies
      run: npm ci 
      
    - name: Install global packages
      run: npm i -g ionic cordova  

    - name: Add iOS platform
      run: ionic cordova resources && ionic cordova platform add ios

    - name: Build iOS
      run: ionic cordova build ios --prod

      
