name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}        
        stale-issue-message: 'Thanks for the issue! This issue is being closed due to inactivity. If this is still an issue with the latest version of Stack App, please create a new issue and ensure the template is fully filled out.'
        stale-pr-message: 'Thanks for the pull request! This pull request is being closed due to inactivity.'
        days-before-stale: 30
        days-before-close: 0
        exempt-issue-label: 'assigned''help wanted''researching''planned'
        exempt-pr-label: 'awaiting approval''researching''planned'
        stale-issue-label: 'inactive'
        stale-pr-label: 'inactive'
