name: Update Angular dependencies

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies
        uses: tinesoft/ngx-uptodate@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
